#! /usr/bin/bash

# # get the project dir name
# if [ -z "$1" ]; then
#   echo "Error: Enter project root directory, starting project at: $(pwd)"
#   # add option to start project in the current directory
#   # exit 1
# fi
# cd to that directory
project_path=$(pwd)
project_name=$(pwd | awk -F/ '{print $(NF-1)"/"$NF}')
# start a new tmux session, or attach to one if already exists
tmux new-session -d -s "$project_name" -c "$project_path"
# start a server window
tmux rename-window -t "$project_name":0 'server'
if [[ -f "./package.json" ]]; then
  # handle a bun project
  if [[ -f "./bun.lock" ]]; then
    echo "Found a bun.lock file, starting a server with bun run dev..."
    tmux send-keys -t "$project_name":server "bun run dev" C-m
  # handle a vite project
  elif [[ -f "vite.config.js" || -f "vite.config.ts" ]]; then
    echo "starting server with npm run dev"
    tmux send-keys -t "$project_name":server "npm run dev" C-m
  fi
else
  echo "./package.json not found, did not start a server..."
fi
# start a nvim editor
tmux new-window -t "$project_name" -n 'editor' -c "$project_path"
tmux send-keys -t "$project_name":editor "nvim" C-m
tmux attach-session -t "$project_name"
