#! /usr/bin/bash

# get the project dir name
if [ -z "$1" ]; then
  echo "Error: Enter project root directory, starting project at: $(pwd)"
  # add option to start project in the current directory
  # exit 1
fi

# cd to that directory
project_path=$(pwd)
project_name=$(pwd | awk -F/ '{print $(NF-1)"/"$NF}')

# start a new tmux session, or attach to one if already exists
tmux new-session -d -s "$project_name" -c "$project_path"

# start a nvim editor window
tmux rename-window -t "$project_name":0 'editor'
tmux send-keys -t "$project_name":editor "nvim" C-m

# start a server window if package.json found
if [[ -f "./package.json" ]]; then
  tmux new-window -t "$project_name" -n 'server' -c "$project_path"
  #   # handle a bun project
  if [[ -f "./bun.lock" ]]; then
    echo "Found a bun.lock file, starting a server with bun run dev..."
    tmux send-keys -t "$project_name":server "bun run dev" C-m
  # handle a vite project
  elif [[ -f "vite.config.js" || -f "vite.config.ts" ]]; then
    echo "starting server with npm run dev"
    tmux send-keys -t "$project_name":server "npm run dev" C-m
  else
    echo "found ./package.json bun cant start a server with bun run dev or npm run dev..."
  fi
fi
tmux select-window -t 'editor'
tmux attach-session -t "$project_name"
